// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_zWd1vSSMrzbWoDgEIraZfydUNyYuPdA',
    appId: '1:648824532681:web:6dbe51d3ce06368a32e718',
    messagingSenderId: '648824532681',
    projectId: 'repuestazo-fb781',
    authDomain: 'repuestazo-fb781.firebaseapp.com',
    storageBucket: 'repuestazo-fb781.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApdeGd14CE6mvH_ju5mMk0eGzcYLo5nfM',
    appId: '1:648824532681:android:32aa8a7cd21d86a332e718',
    messagingSenderId: '648824532681',
    projectId: 'repuestazo-fb781',
    storageBucket: 'repuestazo-fb781.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6lFAmPbR9gR4lkP4E_Rhd-eV1RtrV4lE',
    appId: '1:648824532681:ios:71a37c147c976db132e718',
    messagingSenderId: '648824532681',
    projectId: 'repuestazo-fb781',
    storageBucket: 'repuestazo-fb781.appspot.com',
    androidClientId: '648824532681-9c2gd4nl1cnh71toirtaco4aav6bqddc.apps.googleusercontent.com',
    iosClientId: '648824532681-9dl2o02pa7mrsfi6i4oourds4osrjlmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.repuestazo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6lFAmPbR9gR4lkP4E_Rhd-eV1RtrV4lE',
    appId: '1:648824532681:ios:71a37c147c976db132e718',
    messagingSenderId: '648824532681',
    projectId: 'repuestazo-fb781',
    storageBucket: 'repuestazo-fb781.appspot.com',
    androidClientId: '648824532681-9c2gd4nl1cnh71toirtaco4aav6bqddc.apps.googleusercontent.com',
    iosClientId: '648824532681-9dl2o02pa7mrsfi6i4oourds4osrjlmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.repuestazo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_zWd1vSSMrzbWoDgEIraZfydUNyYuPdA',
    appId: '1:648824532681:web:278d23b4039140d732e718',
    messagingSenderId: '648824532681',
    projectId: 'repuestazo-fb781',
    authDomain: 'repuestazo-fb781.firebaseapp.com',
    storageBucket: 'repuestazo-fb781.appspot.com',
  );

}